CREATE DATABASE IF NOT EXISTS restaurante DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE restaurante;

CREATE TABLE reservas (id INT AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL,telefono VARCHAR(20) NOT NULL,comensales VARCHAR(10) NOT NULL,comentarios TEXT,fecha_reserva DATETIME DEFAULT CURRENT_TIMESTAMP);